import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'admin',
      email: 'admin@admin.com',
      password: bcrypt.hashSync('oussamabessaad', 8),
      isAdmin: true,
    },
    {
      name: 'oussama',
      email: 'oussama@example.com',
      password: bcrypt.hashSync('oussamabessaad', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
      tags: ['Shirts'],
    },
    {
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
      tags: ['Shirts'],
    },
    {
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
      tags: ['Shirts'],
    },
    {
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
      tags: ['Pants'],
    },
    {
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
      tags: ['Pants'],
    },
    {
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
      tags: ['Pants'],
    },
    {
      name: 'Avocado, Large',
      category: 'vegetables',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/veges/avocado_dzlpve.png',
      price: .69,
      countInStock:55,
      description: '1 ct',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['vegetables'],
    },
    {
      name: 'Cucumbers',
      category: 'vegetables',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/veges/Cucumbers_tgmdlm.png',
      price: 1.20,
      countInStock:66,
      description: '1 ct',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['vegetables'],

    },
    {
      name: 'Green Bell Pepper',
      category: 'vegetables',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/veges/GreenBellPepper_osd0k5.webp',
      price: .39,
      countInStock:36,
      description: '1 ct',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['vegetables'],
    },
    {
      name: 'Onion Red',
      category: 'vegetables',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/veges/OnionRed_lb82et.webp',
      price: 1.09,
      countInStock:68,
      description: '1 ct',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['vegetables'],
    },
    {
      name: 'Eggplant',
      category: 'vegetables',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668305/veges/Eggplant_oqmxtd.webp',
      price: 1.19,
      countInStock:21,
      description: '1 ct',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['vegetables'],
    },
    {
      name: 'Yams Red',
      category: 'vegetables',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/veges/yamsred_sieqfg.webp',
      price: .79,
      countInStock:44,
      description: '1 ct',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['vegetables'],
    },
    {
      name: 'Green Giant Fresh Carrots',
      category: 'vegetables',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/veges/GreenGiantFreshCarrots_p6vrjx.webp',
      price: .89,
      countInStock: 10,
      description: '1 lb',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['vegetables'],
    },
    // fruits
    {
      name: 'Watermelons Seedless',
      category: 'fruits',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668308/fruits/WatermelonsSeedless_qqyiha.png',
      price: 1.89,
      countInStock:33,
      description: '1 ct',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['fruits'],
    },
    {
      name: 'Large Mangos',
      category: 'fruits',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668307/fruits/mango_acl4iz.png',
      price: .89,
      countInStock:32,
      description: '1 ct',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['fruits'],
    },
    {
      name: 'Honeydew',
      category: 'fruits',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668307/fruits/honeydew_anhihd.webp',
      price: 1.59,
      countInStock:13,
      description: '1 ct',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['fruits'],
    },
    {
      name: 'Pears Bartlett',
      category: 'fruits',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668307/fruits/PearsBartlett_cx5bbo.webp',
      price: .89,
      countInStock:55,
      description: '1 ct',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['fruits'],
    },
    {
      name: 'Sweet Limes',
      category: 'fruits',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668307/fruits/SweetLimes_mz6a9e.webp',
      price: .69,
      countInStock:23,
      description: '1 ct',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['fruits'],
    },
    // meat
    {
      name: 'Chicken Breast Bnls Skinless',
      category: 'meat',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668308/meat/chickenbreast_nw9nug.webp',
      price: 3.49,
      countInStock:12,
      description: '1 pkg',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['meat'],
    },
    {
      name: 'Chicken Drumsticks',
      category: 'meat',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668308/meat/chickendrumsticks_hvur9o.webp',
      price: 1.99,
      countInStock:43,
      description: '1 pkg',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['meat'],
    },
    {
      name: 'Buddig Original Deli Thin Beef',
      category: 'meat',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668308/meat/BuddigOriginalDeliThinBeef_ildno9.webp',
      price: .89,
      countInStock:52,
      description: '1 pkg',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['meat'],
    },
    {
      name: 'Chicken Thighs',
      category: 'meat',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668308/meat/ChickenThighs_oamvvc.jpg',
      price: 5.97,
      countInStock:12,
      description: '1 pkg',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['meat'],
    },
    {
      name: 'Cacique Pork Chorizo',
      category: 'meat',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668308/meat/caciqueporkchorizo_lqzxnk.webp',
      price: 1.19,
      countInStock:23,
      description: '1 pkg',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['meat'],
    },
    // dairy
    {
      name: 'Egglands Best Organic Cage Free Grade A Brown Eggs',
      category: 'dairy',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/dairy/egglandegg_hu5mb8.webp',
      price: 6.39,
      countInStock:25,
      description: '12 ct',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['dairy'],
    },
    {
      name: 'Horizon Organic 2% Milk',
      category: 'dairy',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/dairy/horizonmilk_qvp6as.webp',
      price: 4.99,
      countInStock:26,
      description: '1/2 gal',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['dairy'],
    },
    {
      name: 'Yoplait Original Yogurt Harvest Peach Tub',
      category: 'dairy',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668307/dairy/yoplaitorginalyogurtharvest_agfu6w.webp',
      price: 3.49,
      countInStock:21,
      description: '32 oz',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['dairy'],
    },
    {
      name: 'Shamrock Farms Vitamin D Whole Milk',
      category: 'dairy',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/dairy/shamrockfarmsvitamind_nr2pcg.webp',
      price: 4.69,
      countInStock:12,
      description: '1 gal',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['dairy'],
    },
    {
      name: 'Chobani Plain Non-Fat Greek Yogurt',
      category: 'dairy',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/dairy/chobaniplannonfat_ol4ba5.webp',
      price: 5.70,
      countInStock:43,
      description: '32 oz',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['dairy'],
    },
    {
      name: 'Challenge Butter',
      category: 'dairy',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/dairy/ChallengeButter_fhneqp.webp',
      price: 5.29,
      countInStock: 10,
      description: '16 oz',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['dairy'],
    },
    {
      name: 'SuperPretzel Baked Soft Pretzels',
      category: 'frozen',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668307/frozen/superpretzel_btxubb.webp',
      price: 4.09,
      countInStock: 10,
      description: '6 ct',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['frozen'],
    },
    {
      name: 'Kelloggs Eggo Waffles Homestyle',
      category: 'frozen',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668307/frozen/kellogg_zaxhdn.webp',
      price: 2.89,
      countInStock: 10,
      description: '10 ct',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['frozen'],
    },
    {
      name: 'Red Baron Pizzeria Style Classic Crust Pepperoni Pizza',
      category: 'frozen',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668308/frozen/redbaronclassiccrust_ukezr8.webp',
      price: 4.09,
      countInStock: 10,
      description: '20 oz',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['frozen'],
    },
    {
      name: 'Cool Whip Original Whipped Topping',
      category: 'frozen',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668307/frozen/coolwhip_morivm.webp',
      price: 4.69,
      countInStock: 10,
      description: '16 oz',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['frozen'],
    },
    {
      name: 'El Monterey Beef & Bean Burritos',
      category: 'frozen',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668307/frozen/elmontererybeef_wbtflj.webp',
      price: 4.69,
      countInStock: 10,
      description: '8 ct',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['frozen'],
    },
    // pantry
    {
      name: 'Kraft Original Flavor Macaroni and Cheese',
      category: 'pantry',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668305/pantry/kraft_lcsmiu.webp',
      price: 1.49,
      countInStock: 10,
      description: '7.25 oz',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['pantry'],
    },
    {
      name: 'Rotel Original Diced Tomatoes & Green Chilies',
      category: 'pantry',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668305/pantry/rotel_g2hzjo.webp',
      price: 1.49,
      countInStock: 10,
      description: '12 oz',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['pantry'],
    },
    {
      name: 'Cinnamon Toast Crunch Cereal - General Mills',
      category: 'pantry',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668305/pantry/cinnamon_zitdrc.webp',
      price: 5.79,
      countInStock: 10,
      description: '19.3 oz',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['pantry'],
    },
    {
      name: 'Jiffy Corn Muffin Mix - 8.5',
      category: 'pantry',
      image: '/assets/pantry/jiffy.webp',
      price: .89,
      countInStock: 10,
      description: '8.5 oz',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['pantry'],
    },
    {
      name: 'Jif Creamy Peanut Butter',
      category: 'pantry',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668305/pantry/jifcreamypeanutbutter_bwmyn2.webp',
      price: 3.29,
      countInStock: 10,
      description: '16 oz',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['pantry'],
    },
    {
      name: 'Heinz Easy Squeeze Tomato Ketchup',
      category: 'pantry',
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668305/pantry/heinz_u3vil3.webp',
      price: 3.79,
      countInStock: 10,
      description: '20 oz',
      brand: 'Gomyzone',
      rating: 4.5,
      numReviews: 10,
      tags: ['pantry'],
    }
  ],
};

export default data;
